Repository telerik/kendo-theme-tasks, pull requests merged in 2021-04, with the labels that each got.

#8 Add global hidden attribute ot hide swatches, groups and variables from themebuilder interface
  lib/schemas/themebuilder-swatch.json
  test/schemas/themebuilder-swatch-primer.json
Labels: enhancement

#1 Add logic for generating utils docs
  docs.js
  index.js
  package-lock.json
  package.json
  src/docs/index.js
  src/docs/templates/utils-docs/README.md.njk
  src/docs/utils-docs.js
Labels: CLI:Docs, Enhancement

#9 fix: use opts.file for embedFileBase64
  src/embedFile/embedFileBase64.js
Labels: bug
